### PR TITLE
Add support for 515.1641 on Windows

### PR DESCRIPTION
**Pull request by Absolucy**

### CODE REVIEW

**Review by ZeWaka — CHANGES_REQUESTED** [review]
readme

**Comment by ZeWaka** [comment]
Why are binaries in repo

**Comment by Absolucy** [comment]
because i forgot there wasn't a gitignore

**Review by ZeWaka — APPROVED** [review]

**Comment by ZeWaka** [comment]
apparently this needs zeroes for the in-between versions

**Comment by mafemergency** [comment]
thank you for the effort

**Pull request closed without merging**
