### PR TITLE
Add support for Tracy 0.11.0 and 0.11.1

### PR DESCRIPTION
**Pull request by checkraisefold**
tin
tested & works
https://github.com/wolfpld/tracy/commit/133d52a6dd4e55a74947d1bfea1ef7919742d8d0
https://github.com/wolfpld/tracy/commit/41fc2930434bb2296cc8c255f82bcb731f8c0f06

for 0.11.1:
https://github.com/wolfpld/tracy/commit/8cea63cbcae51742f85c952d83ef1096f9f3e89a
https://github.com/wolfpld/tracy/commit/37bfde51063a9f4c76ced8c199f73c3a97a58fc2
https://github.com/wolfpld/tracy/commit/353545a1e93f165f6dc5a068ac50f66231e5b544

### CODE REVIEW

**Review by ZeWaka — CHANGES_REQUESTED** [review]
need to add to readme

**Comment by checkraisefold** [comment]
@ZeWaka fixed

**Comment by ZeWaka** [comment]
works great, 0.11.1 does exist now and it does error on that btw

**Comment by checkraisefold** [comment]
> works great, 0.11.1 does exist now and it does error on that btw

holy shit they bumped the protocol version by 4 what are they doing

**Comment by checkraisefold** [comment]
@ZeWaka there you go

**Pull request merged**
